enrolment:
  required_columns:
    - date
    - state
    - district
    - pincode
    - age_0_5
    - age_5_17
    - age_18_greater

  numeric_columns:
    - age_0_5
    - age_5_17
    - age_18_greater

demographic:
  required_columns:
    - date
    - state
    - district
    - pincode
    - demo_age_5_17
    - demo_age_17_

  numeric_columns:
    - demo_age_5_17
    - demo_age_17_

biometric:
  required_columns:
    - date
    - state
    - district
    - pincode
    - bio_age_5_17
    - bio_age_17_

  numeric_columns:
    - bio_age_5_17
    - bio_age_17_